src/backend/api/urls.py
from django.urls import include, path
from rest_framework.routers import DefaultRouter

from api.views.answer import answer_create
from api.views.mentors import MentorViewSet
from api.views.problems import problem_create
from api.views.questions import get_question, get_question_for_task_8
from api.views.results import get_results_for_user_by_task
from api.views.tasks import TaskStatusViewSet, TaskViewSet
from api.views.users import UserFromTelegramViewSet

app_name = "api"

router = DefaultRouter()

router.register(r"users", UserFromTelegramViewSet, basename="users")
router.register(
    r"users/(?P<telegram_id>\d+)/tasks", TaskStatusViewSet, basename="user-tasks"
)
router.register(r"mentors", MentorViewSet, basename="mentors")
router.register(r"tasks", TaskViewSet, basename="tasks")

urlpatterns = [
    path("v1/", include(router.urls)),
    path(
        "v1/users/<int:telegram_id>/problems/",
        problem_create,
        name="problem_create",
    ),
    path(
        "v1/users/<int:telegram_id>/tasks/<int:task_number>/answers/",
        answer_create,
        name="answer_create",
    ),
    path(
        "v1/users/<int:telegram_id>/tasks/<int:task_number>/results/",
        get_results_for_user_by_task,
        name="get_results_for_user_by_task",
    ),
    path(
        "v1/task/<int:task_number>/question/<int:question_number>/",
        get_question,
        name="get_question",
    ),
    path(
        "v1/task_8_question/<int:question_number>/",
        get_question_for_task_8,
        name="get_question_for_task_8",
    ),
]

src/backend/backend/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path("tinymce/", include("tinymce.urls")),
    path("admin/", include("info_pages.urls")),
    path("admin/", admin.site.urls),
    path("api/", include("api.urls")),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

src/backend/info_pages/urls.py
from django.urls import path

from info_pages.views import UserDetailView

app_name = "info_pages"

urlpatterns = [
    path(
        "info/user/<int:telegram_id>/",
        UserDetailView.as_view(),
        name="taskstatus-list",
    ),
]

src/backend/info_pages/views.py
from django.db.models import Prefetch
from django.views.generic import DetailView

from api.models import Answer, ResultStatus, UserFromTelegram
from info_pages.mixins import IsStaffMixin


class UserDetailView(IsStaffMixin, DetailView):
    queryset = UserFromTelegram.objects.select_related("mentor__user")
    slug_field = "telegram_id"
    slug_url_kwarg = "telegram_id"
    template_name = "info_pages/user.html"

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)

        task_statuses = (
            self.object.tasks.select_related("task")
            .prefetch_related(
                Prefetch(
                    "result",
                    queryset=ResultStatus.objects.select_related("result"),
                ),
                Prefetch(
                    "answers",
                    queryset=Answer.objects.select_related("question").prefetch_related(
                        "question__choices",
                    ),
                ),
            )
            .all()
        )
        context["tasks"] = task_statuses

        passed_tasks = []
        unfinished_tasks = []
        for status in task_statuses:
            if status.is_done:
                passed_tasks.append(str(status.task.number))
            else:
                unfinished_tasks.append(str(status.task.number))
        context["passed_tasks"] = ", ".join(passed_tasks)
        context["unfinished_tasks"] = ", ".join(unfinished_tasks)

        context["test_summary"] = self.object.test_summary

        return context

src/backend/templates/info_pages/includes/header.html
{% load static %}
<nav class="navbar navbar-expand-lg" style="background-color: #f8bc43;">
  <div class="container">
    <a class="navbar-brand d-flex align-items-center" href="{% url 'admin:index' %}">
      <img src="{% static 'logo.png' %}" alt="логотип" width="56" height="52" class="d-inline-block align-text-middle" id="logo">
      <div class="d-inline-block ms-2" style="line-height: 1;">
        <span class="fs-5 d-block">Помогаем реализовать</span>
        <span class="fs-5 d-block">твои таланты</span>
      </div>
    </a>
    <div class="collapse navbar-collapse" id="navbarNav">
      <ul class="navbar-nav">
        <li class="nav-item">
        {% if request.GET.questions %}
          <a class="nav-link" href="{% url 'info_pages:taskstatus-list' telegram_id=object.telegram_id %}">Спрятать вопросы</a>
        {% else %}
          <a class="nav-link" href="{% url 'info_pages:taskstatus-list' telegram_id=object.telegram_id %}?questions=true">Показать вопросы</a>
        {% endif %}
        </li>
        <li class="nav-item">
          <a class="nav-link" onclick="window.print()">Печать</a>
        </li>
      </ul>
    </div>
  </div>
</nav>